### ISSUE TITLE
AGM-62 Clipping through wing

### ISSUE THREAD

**Issue by dboshardy** [LevelPulse/A-4-Skyhawk#1]
When loaded, this loads on the stock pylon and not the extended pylon, so it's rear fins clip about 5-6 inches through the wing.

**Comment by indiadamjones** [comment]
This issue looks closed to me, but honestly, I'm not sure.  If this ordnance is still clipping, maybe we can get a picture here, so we can see what's going on.  Otherwise I think it's safe to close this.

**Comment by indiadamjones** [comment]
Re-opening as modelling request.
