### ISSUE TITLE
In-Game Wallpaper

### ISSUE THREAD

**Issue by LevelPulse** [LevelPulse/A-4-Skyhawk#13]

**Comment by callmepartario** [comment]
i've added an early idea of what something could look like in addition to some other small ui updates today. things will get more solid looking as the unwrap is finalized enough to get some panel lines and liveries going. there are still the load screens and more to do.

**Comment by indiadamjones** [comment]
I'm calling this closed.  Plusnine, can you repost for any missing screens?  Great work on the current screens, looks great!
