### ISSUE TITLE
AGM-62 Walleye

### ISSUE THREAD

**Issue by ttaylor0024** [LevelPulse/A-4-Skyhawk#20]
Unpowered bomb guided with nose mounted TV camera

The Walleye's camera sent an image of the target to the pilot's television screen. Once the pilot "locked" onto the target, he launched the weapon. The Walleye's onboard guidance system independently compared the locked image with the current image and made course corrections. Since the pilot did not have to control the bomb all the way to the target, the Walleye was known as a "fire and forget" weapon.

TECHNICAL NOTES:
Weight: 1,100 lbs.
Range: 16 miles
Warhead: 825-lb. MK 58 linear shaped-charge

http://www.nationalmuseum.af.mil/Visit/MuseumExhibits/FactSheets/Display/tabid/509/Article/195663/martin-marietta-agm-62-walleye-i.aspx

**Comment by LevelPulse** [comment]
The variant we are doing didn't have a TV screen. Unfortunately :/

**Comment by ttaylor0024** [comment]
Well then nevermind... Haha please delete
