### ISSUE TITLE
Mk-82 Snakeeye only on left inner pylon

### ISSUE THREAD

**Issue by dboshardy** [LevelPulse/A-4-Skyhawk#22]
Testing this yesterday I noticed that you could only load Mk-82 Snakeeye on a 6x MER on the left inner pylon (pylon 4).  The Mk. 81 Snakeeye is not available on any pylon. 

According to [this doc,](https://drive.google.com/drive/u/0/folders/0B9E69EvOMFXjZUE4elpoTEUzZ0k) the Mk 81 & 82 Snakeeye should be available on all pylons.

**Comment by kryb** [comment]
It's WIP, and can be fixed in 10 seconds. It will be done once it's needed.

**Comment by dboshardy** [comment]
Totally fine. Just wanted to record it so we can keep it in mind when the
time comes.

**Comment by LevelPulse** [comment]
I've fixed this locally, i will commit this when i get home.

As of right now, i'll be using placemarkers for the pylons until they've either been added/coded into the game.
