### ISSUE TITLE
Standard Flight Model 

### ISSUE THREAD

**Issue by dboshardy** [LevelPulse/A-4-Skyhawk#23]
Go through and verify the SFM tables and consts.  If already completed, tweak to match performance.

**Comment by dboshardy** [comment]
@kryb is this done already?

**Comment by kryb** [comment]
no, not for the SFM
I did it quickly, to have an aircraft that was in the range of what a skyhawk would do, but it's not tweaked, at all.

**Comment by dboshardy** [comment]
To complete with this we must implement:
- Radar Cross-Section
- IR Emissions 
- Engine
- Fuel Consumption 
- Damage model.

**Comment by dboshardy** [comment]
And sensors

**Comment by indiadamjones** [comment]
I think SFM needs to be a github tag, it seem too broad for a single issue.  Let's break apart into some smaller bites, and tag with SFM.  Then, once that's arranged, let's close this original issue, Thanks.

**Comment by indiadamjones** [comment]
Please re-post as smaller issues.
