### ISSUE TITLE
Translating weapon/fm data

### ISSUE THREAD

**Issue by LevelPulse** [LevelPulse/A-4-Skyhawk#30]
```
-- struct WEAPONS_API Rocket_Const // Ракетные постоянные и настройки для законов управления. 
            -- // Характеристики ракеты
    -- unsigned char Name_;     //  имя ракеты
    -- int           Escort_;   //  сопровождение: 0 - нет, 1 - ЛА пуска, 2 - другой ЛА, 3 - c земли
    -- int           Head_Type_;// Тип головки самонаведения (ГСН)(cм выше) 
	--				sigma = {x, y, z}, максимальная ошибка прицеливания в метрах, в координатах цели. x - продольная ось цели, y - вертиальная ось цели, z - поперечная ось цели
    -- float         M_;        //  полная масса в кг
    -- float         H_max_;    //  максимальная высота полета. 
    -- float         H_min_;    //  минимальная высота полета.  
    -- float         Diam_;     //  Диаметр корпуса в мм 
    -- int           Cx_pil;    //  Cx как подвески
    -- float         D_max_;    //  максимальная дальность пуска на малой высоте
    -- float         D_min_;    //  минимальная дальность пуска
    -- bool          Head_Form_;// false - полусферическая форма головы, 
                   -- // true   - оживальная (~коническая)
    -- float         Life_Time_;//  время жизни (таймер самоликвидации), сек
    -- double        Nr_max_;   // Максимальная перегрузка при разворотах
    -- float         v_min_;    // Минимальная скорость. 
    -- float    v_mid_;  // Средняя скорость
    -- float         Mach_max_; // Максимальное число Маха.
    -- float         t_b_;      // время включения двигателя
    -- float         t_acc_;    // время работы ускорителя
    -- float         t_marsh_;  // время работы в маршевом режиме
    -- float         Range_max_;// максимальная дальность пуска на максимальной высоте
    -- float         H_min_t_;  // минимальная высота цели над рельефом, м.     
    -- float         Fi_start_; // угол сопровождения и визирования при пуске  
    -- float         Fi_rak_;   // допустимый угол ракурса цели (rad)
    -- float         Fi_excort_;// угол сопровождения (визир.) цели ракетой.
    -- float          Fi_search_;// предельный угол свободного поиска
    -- float          OmViz_max_;// предельная скорость линии визирования
    -- float         Damage_;// повреждение, наносимое при прямом попадании
	-- /*   int           Engine_Type_; // тип двигателя: 1 - твердотопливный;
                             -- // 2 - Жидкостный Ракетный Двигатель(РД)(ЖРД); 
                             -- // 3 - Прямоточный Воздушный РД ; 
                             -- // 4 - ускоритель-1+ЖРД.
                             -- // 5 - турбореактивный
                             -- // 6 - турбореактивный + ускоритель 
    -- int           Stage_;    // количество ступеней.*/
    -- float         X_back_;   // координаты центра сопла в осях ракеты
    -- float         Y_back_; 
    -- float         Z_back_;
	-- float		 X_back_acc_; // координаты центра сопла ускорителя в осях ракеты
	-- float		 Y_back_acc_;
	-- float		 Z_back_acc_;
    -- float          Reflection;   // эффективная поверхность радиоотражения, квадратные метры

    -- // Kill distances - this distance is used to fire a fuze
    -- double        KillDistance;

    -- // These are warheads used to simulate explosions
    -- // Due to the architecture of blocksim we have to use two schemes - 
    -- // one for server object (which actually makes damage), and other for
    -- // client object (which does not make any damage)
	
	-- Мгновенный угол обзора ракет:
	-- ИК ГСН +- 1 градус
	-- РС ГНС +- 5 градусов
```

**Comment by dboshardy** [comment]
Best I could do. @uboats says he might be able to get the rest translated (or a better translation than I can do).

```-- struct WEAPONS_API Rocket_Const // 
            -- // rocket characteristics
    -- unsigned char Name_;     //  rocket name
    -- int           Escort_;   //  ??Escort: 0 - none, 1 - ЛА пуска, 2 - другой ЛА, 3 - c земли??
    -- int           Head_Type_;// Seeker head type (ГСН)(cм выше) 
    --              sigma = {x, y, z}, ???max aim error in meters, in coordinates to the target, x - logitudinal axis to the target, y - vertical axis to the target, z - lateral axis to the target???
    -- float         M_;        //  total mass in kg
    -- float         H_max_;    //  max operational altitude. 
    -- float         H_min_;    //  min operational altitude. 
    -- float         Diam_;     //  diameter of housing in mm
    -- int           Cx_pil;    //  Cx как подвески
    -- float         D_max_;    //  max launch range at min altitude
    -- float         D_min_;    //  min launch range
    -- bool          Head_Form_;// false - hemispherical head, 
                   -- // true   - ??оживальная?? (~conical)
    -- float         Life_Time_;//  life time (self-destruct timer), seconds
    -- double        Nr_max_;   // max turn acceleration
    -- float         v_min_;    // min speed
    -- float    v_mid_;  // average speed
    -- float         Mach_max_; // max max number
    -- float         t_b_;      // ???motor response time???
    -- float         t_acc_;    // acceleration time
    -- float         t_marsh_;  // ????time while operating in mid-course mode????
    -- float         Range_max_;// max launch range at max altitude
    -- float         H_min_t_;  // min altitude of target above ground    
    -- float         Fi_start_; // ???oresight angle and tracking before launch???
    -- float         Fi_rak_;   // ???allowable angle to the target (radians)
    -- float         Fi_excort_;// ???track angle (boresight?) to the target 
    -- float          Fi_search_;// ???limiting search angle 
    -- float          OmViz_max_;// ???limiting tracking speed???
    -- float         Damage_;// damage inflicted by direct hit
    -- /*   int           Engine_Type_; // engine type: 1 - solid fuel;
                             -- // 2 - liquid fuel; 
                             -- // 3 - ram air; 
                             -- // 4 - ??accelerator??
                             -- // 5 - turbojet;
                             -- // 6 - ??turbojet + accelerator/afterburner??
    -- int           Stage_;    // number of stages
    -- float         X_back_;   // coordinates of rocket nozzle center axis
    -- float         Y_back_; 
    -- float         Z_back_;
    -- float         X_back_acc_; // ??coordinates of the center of the accelerator nozzle??
    -- float         Y_back_acc_;
    -- float         Z_back_acc_;
    -- float          Reflection;   // effective surface radar reflection (RCS?), square meters

    -- // Kill distances - this distance is used to fire a fuze
    -- double        KillDistance;

    -- // These are warheads used to simulate explosions
    -- // Due to the architecture of blocksim we have to use two schemes - 
    -- // one for server object (which actually makes damage), and other for
    -- // client object (which does not make any damage)

    -- Immediate launch angle??
    -- IR seeker +- 1 degree
    -- РС ГНС +- 5 degrees?????```

**Comment by uboats** [comment]
this does not show all parameters, we need to collect all of them from some new instances (introduce new parameters) @dboshardy

**Comment by LevelPulse** [comment]
If that could be done @uboats i would appreciate it!

**Comment by uboats** [comment]
EN in Original file might be mis-translate from RU. And original RU may have typos:
below are comments made by my friend
he is still working on it, not finished yet
------

1. int           Escort_;   //  ??Escort: 0 - none, 1 - ЛА пуска, 2 - другой ЛА, 3 - c земли??

ЛА пуска - an aircraft that launches a missile ( or a rocket as I guess)

другой ЛА - another aircraft

c земли - from the ground (must be launch from the ground (SAM maybe)).

//  сопровождение: ??Escort:

I think it's incorrect. сопровождение: - tracking.

2. Cx как подвески - Cx is the same as payload Cx.

3. РС ГНС - radar homing seeker

4. оживальная -  ogive (a shape of missile head: https://en.wikipedia.org/wiki/Ogive)

TBC

**Comment by uboats** [comment]
Here is completed one, if any unclear, please let me know. Also thank my friend Alexey very much for the help!
----------------
-- struct WEAPONS_API Rocket_Const // Ракетные постоянные и настройки для законов управления. 
            -- // missile characteristics
    -- unsigned char Name_;     //  missile name 
    -- int           Escort_;   //  tracking: 0 - none, 1 - an aircraft that launches a missile, 2 - another aircraft, 3 - from the ground (obviously launching)
    -- int           Head_Type_;// head seeker type (seeker)(see above) 
    --              sigma = {x, y, z}, max aimшing error in meters, in coordinates of the target (I think it means coordinates relative the target centre) , x -logitudinal axis of the target, y - vertical axis of the target, z - lateral axis of the target
    -- float         M_;        //  total weight (or wet weight) in kg
    -- float         H_max_;    //  max operational altitude. 
    -- float         H_min_;    //  min operational altitude.  
    -- float         Diam_;     //  body diameter in mm 
    -- int           Cx_pil;    //  Cx is similar to payload Cx.
    -- float         D_max_;    //  max launch range at min altitude
    -- float         D_min_;    //  min launch range
    -- bool          Head_Form_;// false - hemispherical head seeker shape, 
                   -- // true   - ogive  (~conical)  -- head seeker shape
    -- float         Life_Time_;//   life time (self-destruct timer), seconds
    -- double        Nr_max_;   // max turn acceleration
    -- float         v_min_;    // min speed 
    -- float    v_mid_;  // average speed
    -- float         Mach_max_; // max Mach number
    -- float         t_b_;      // time of the engine switch on (when the engine should be switched on)
    -- float         t_acc_;    // acceleration time (firing time)
    -- float         t_marsh_;  // firing time of the main propulsion motor
    -- float         Range_max_;// max launch range at max altitude
    -- float         H_min_t_;  // min altitude of target above ground      
    -- float         Fi_start_; // tracking angle and sight aiming angle while launching
    -- float         Fi_rak_;   // allowable target-aspect ratio angle (rad)
    -- float         Fi_excort_;// missile tracking angle (tracking angle from the missile to the target)
    -- float          Fi_search_;// limit angle of free search
    -- float          OmViz_max_;// limit speed of sight line
    -- float         Damage_;// damage inflicted by direct hit
    -- /*   int           Engine_Type_; // engine type: 1 - solid fuel;
                             -- // 2 - liquid fuel; 
                             -- // 3 - ram air ; 
                             -- // 4 - booster (solid fuel engine) + liquid fuel engine.
                             -- // 5 - turbojet
                             -- // 6 - turbojet + booster
    -- int           Stage_;    //  number of stages
    -- float         X_back_;   //  coordinates of missile nozzle center axis
    -- float         Y_back_; 
    -- float         Z_back_;
    -- float         X_back_acc_; // coordinates of booster nozzle center axis
    -- float         Y_back_acc_;
    -- float         Z_back_acc_;
    -- float          Reflection;   // effective surface radar reflection (RCS), square meters

    -- // Kill distances - this distance is used to fire a fuze
    -- double        KillDistance;

    -- // These are warheads used to simulate explosions
    -- // Due to the architecture of blocksim we have to use two schemes - 
    -- // one for server object (which actually makes damage), and other for
    -- // client object (which does not make any damage)

    -- instant missile look-up angle:
    -- IR seeker +- 1 degrees
    -- Radar homing seeker +- 5 degrees

**Comment by LevelPulse** [comment]
This is now closed.
