### ISSUE TITLE
Flaps clipping the fuel pod when mounted on pylon 2 and 4

### ISSUE THREAD

**Issue by indiadamjones** [LevelPulse/A-4-Skyhawk#31]
![image_044](https://cloud.githubusercontent.com/assets/4664873/13229152/7065fab0-d96d-11e5-8d0f-13f9d8467ccb.jpg)

**Comment by gospadin** [comment]
Looking at various reference pictures, the back the fuel tanks is too high.  NATOPS manual makes no statements on flap settings limitations when carrying fuel tanks (or weapons), and as such, I believe our mounting angle of the fuel tanks is incorrect.  Not sure if this requires a model change or what.

**Comment by gospadin** [comment]
![image](https://cloud.githubusercontent.com/assets/16710755/13277997/08ef2c44-da8a-11e5-9cd6-655041798d59.png)

**Comment by kryb** [comment]
![a-4e_skyhawk_from_va-45_in_flight_in_1972](https://cloud.githubusercontent.com/assets/16743151/13317690/b4dc9bc2-dbb6-11e5-98b2-f52f8ebe1546.jpg)
Here the tank is pretty straight. Hard to tell wether or not it should be at an angle...

**Comment by LevelPulse** [comment]
Problem is now solved by @kryb and @gospadin commit.

**Comment by kryb** [comment]
Fixed.
