### ISSUE TITLE
built-in canopy open/close command doesn't close canopy in external view

### ISSUE THREAD

**Issue by gospadin** [LevelPulse/A-4-Skyhawk#34]
it's not possible to change the canopy in external view

this means a cold start will rip off the canopy, which makes for a noisy flight

**Comment by kryb** [comment]
Not a bug, it's an animation. Almost no animations are done for the player aicraft. They all have to be coded in the SSM.

**Comment by kryb** [comment]
The canopy can't be open/closed now, following the fix for the infinite jettison of the cockpit mid air.

**Comment by gospadin** [comment]
canopy works fine for me

can you double check your keybindings?  are you air or ground starting?

(i'm using the ctrl-c default)

**Comment by kryb** [comment]
Is has been fixed
