### ISSUE TITLE
Spoiler deflection angle

### ISSUE THREAD

**Issue by kryb** [LevelPulse/A-4-Skyhawk#37]
Right now the spoiler's have an arbitrary angle of about 50°.

Does anyone have the right number ?

**Comment by indiadamjones** [comment]
https://www.youtube.com/watch?v=7NOk2u592_0

From this video I calculated 56.38 degrees.

![image_019](https://cloud.githubusercontent.com/assets/4664873/13581205/bb7653ea-e473-11e5-8dd5-4437fa1dafb7.jpg)

**Comment by indiadamjones** [comment]
56 degrees :)
