### ISSUE TITLE
Huffer tube extends through the body of stores attached to the center pylon

### ISSUE THREAD

**Issue by gospadin** [LevelPulse/A-4-Skyhawk#44]
Whether a fuel tank, rockets, or a TER of bombs, the huffer air tube extends through the stores attached to the center pylon.

![image](https://cloud.githubusercontent.com/assets/16710755/13708190/77babdc2-e76a-11e5-9d74-e67498ebfe66.png)

**Comment by indiadamjones** [comment]
I'm going to make a custom attachment of your suggestion on this.

**Comment by indiadamjones** [comment]
Repaired, but I still see a random cylinder around the APU exhaust.  Will take it up later, on another issue.
