### ISSUE TITLE
APC AN/ASN-54 (autopilot)

### ISSUE THREAD

**Issue by LevelPulse** [LevelPulse/A-4-Skyhawk#7]

**Comment by indiadamjones** [comment]
This doesn't appear to be an A-4E feature...Approach Power Control Set; manufactured by Teledyne; used in A-6A, EA-6B, TA-4J, F-4 see here: http://www.designation-systems.net/usmilav/jetds/an-asn.html

**Comment by gospadin** [comment]
are we sure we want to close?  the SAC for the A-4E states it had an
AN/ASN-54 autopilot, and the controls for it are definitely on the sample
instrument panel

**Comment by indiadamjones** [comment]
I can only find Approach Power Compensator in NATOPS. The AN/ASN-54, is sometimes a component of that system but I can't find any information on it anywhere at all for A-4.  I did find some information about it for an F-4, it's not typical autopilot with is Automatic Flight Control Systems AFCS, this is Approach Power Comepensator for A-4E, if the ASN-54 is back there running, they forgot to mention it in NATOPS for E/F/G Variants.
